# Generated by Django 4.0.3 on 2022-03-14 10:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titel', max_length=150)),
                ('body', ckeditor.fields.RichTextField(blank=True, help_text='Tekst', null=True)),
                ('image', models.ImageField(blank=True, help_text="Pænest hvis billedet er kvadratisk. <a href='https://croppola.com/' target='_blank'>Kan f.eks. ændres her.</a>", null=True, upload_to='images/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
