# Generated by Django 4.0.3 on 2022-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='admin_name',
            field=models.CharField(default='Post', help_text='Titel', max_length=150),
        ),
    ]
