# Generated by Django 4.0.3 on 2022-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name_plural': 'Kontaktinfo'},
        ),
        migrations.AddField(
            model_name='details',
            name='show_phone',
            field=models.BooleanField(default=False, help_text='Offentliggør telefonnummer på hjemmesiden'),
        ),
    ]
